import { RoleProfile } from './models';

export const ROLE_PROFILES: RoleProfile[] = [
  {
    id: 'superadmin',
    roleName: 'SuperAdmin',
    userName: 'Carlos Mejía',
    initials: 'CM',
    scopeLabel: 'Sistema nacional',
    scopeDetail: 'Honduras · todos los territorios',
    privacyLabel: 'Administración global',
    privacyDetail: 'Acciones técnicas y excepcionales auditadas.',
    dashboardMeta: {
      eyebrow: 'ADMINISTRACIÓN GLOBAL · HONDURAS',
      title: 'Control general del sistema',
      description: 'Estructura, usuarios, catálogos y disponibilidad operativa nacional.',
    },
    navItems: ['Inicio', 'Administración', 'Redes', 'Mapas', 'Reportes y exportaciones'],
    metrics: [
      {
        label: 'Regiones operativas',
        value: '1 / 18',
        detail: 'Cortés activa en el piloto',
        tone: 'green',
      },
      {
        label: 'Usuarios activos',
        value: '86',
        detail: '8 perfiles institucionales',
        tone: 'blue',
      },
      { label: 'Establecimientos', value: '12', detail: 'Todos en Puerto Cortés', tone: 'purple' },
      {
        label: 'Acciones auditables',
        value: '3',
        detail: 'Requieren revisión técnica',
        tone: 'amber',
      },
    ],
    tasks: [
      {
        title: 'Validar configuración de Región de Cortés',
        detail: 'Revisar alcance, catálogos y responsables regionales.',
        status: 'Configuración',
        target: 'Administración',
      },
      {
        title: 'Completar coordenadas institucionales',
        detail: '12 establecimientos pendientes de validación geográfica.',
        status: 'Territorio',
        target: 'Mapas',
      },
      {
        title: 'Revisar acciones excepcionales',
        detail: 'Tres reaperturas registradas en auditoría.',
        status: 'Auditoría',
      },
    ],
    permissions: [
      'Administrar toda la estructura territorial',
      'Gestionar usuarios, roles y permisos globales',
      'Publicar catálogos y configuraciones nacionales',
    ],
    restrictions: [
      'No sustituye la aprobación institucional de Nivel Central',
      'No obtiene acceso clínico individual de forma implícita',
    ],
    workflow: [
      'Configurar sistema',
      'Activar territorios',
      'Asignar administradores',
      'Auditar operación',
    ],
    primaryLabel: 'Administrar territorios',
    primaryTarget: 'Administración',
  },
  {
    id: 'central-validator',
    roleName: 'Admin o Validador Central',
    userName: 'Dra. Elena Pineda',
    initials: 'EP',
    scopeLabel: 'Nivel Central',
    scopeDetail: 'Honduras · información consolidada nacional',
    privacyLabel: 'Vista nacional agregada',
    privacyDetail: 'Sin acceso a registros individuales ITS 1.',
    dashboardMeta: {
      eyebrow: 'NIVEL CENTRAL · HONDURAS',
      title: 'Seguimiento nacional ITS',
      description: 'Revisión regional, consolidación nacional e indicadores institucionales.',
    },
    navItems: [
      'Inicio',
      'Bandeja de revisión',
      'Consolidados',
      'Redes',
      'Mapas',
      'Reportes y exportaciones',
      'Administración',
    ],
    metrics: [
      {
        label: 'Regiones recibidas',
        value: '1 / 18',
        detail: 'Piloto activo en Cortés',
        tone: 'green',
      },
      { label: 'En revisión', value: '1', detail: 'Consolidado regional', tone: 'blue' },
      { label: 'Casos consolidados', value: '184', detail: 'Julio 2026', tone: 'purple' },
      { label: 'Observaciones', value: '2', detail: 'Pendientes de respuesta', tone: 'amber' },
    ],
    tasks: [
      {
        title: 'Revisar consolidado de Cortés',
        detail: 'Validar integridad y consistencia antes de aprobar.',
        status: 'En revisión',
        target: 'Bandeja de revisión',
      },
      {
        title: 'Preparar consolidado nacional',
        detail: 'Disponible al completar la revisión regional.',
        status: 'Pendiente',
        target: 'Consolidados',
      },
      {
        title: 'Analizar mapa nacional',
        detail: 'Comparar tendencias agregadas por región.',
        status: 'Análisis',
        target: 'Mapas',
      },
    ],
    permissions: [
      'Revisar y devolver consolidados regionales',
      'Aprobar información regional',
      'Generar consolidado nacional',
    ],
    restrictions: ['No administra la configuración técnica global', 'No consulta ITS 1 individual'],
    workflow: ['Recibir regiones', 'Validar calidad', 'Aprobar consolidado', 'Publicar nacional'],
    primaryLabel: 'Abrir revisión nacional',
    primaryTarget: 'Bandeja de revisión',
  },
  {
    id: 'regional-superadmin',
    roleName: 'SuperAdmin Regional',
    userName: 'Lic. Roberto Lagos',
    initials: 'RL',
    scopeLabel: 'Región de Cortés',
    scopeDetail: 'Región asignada y todos sus niveles dependientes',
    privacyLabel: 'Administración regional',
    privacyDetail: 'Gestión limitada a Cortés y con auditoría.',
    dashboardMeta: {
      eyebrow: 'SUPERADMIN REGIONAL · CORTÉS',
      title: 'Gestión integral de la región',
      description:
        'Operación regional y administración de municipios, establecimientos y usuarios.',
    },
    navItems: [
      'Inicio',
      'Bandeja de revisión',
      'Consolidados',
      'Redes',
      'Mapas',
      'Reportes y exportaciones',
      'Administración',
    ],
    metrics: [
      { label: 'Municipios activos', value: '1', detail: 'Puerto Cortés en piloto', tone: 'green' },
      {
        label: 'Establecimientos',
        value: '12',
        detail: 'Catálogo institucional vigente',
        tone: 'blue',
      },
      {
        label: 'Usuarios regionales',
        value: '18',
        detail: 'Dentro del alcance asignado',
        tone: 'purple',
      },
      {
        label: 'Pendientes críticos',
        value: '4',
        detail: 'Operación y configuración',
        tone: 'amber',
      },
    ],
    tasks: [
      {
        title: 'Revisar consolidado de Puerto Cortés',
        detail: 'El municipio reportó 184 casos en el período.',
        status: 'Operación',
        target: 'Bandeja de revisión',
      },
      {
        title: 'Asignar responsables institucionales',
        detail: 'Dos establecimientos requieren responsable activo.',
        status: 'Usuarios',
        target: 'Administración',
      },
      {
        title: 'Validar ubicación de establecimientos',
        detail: 'Confirmar los 12 puntos antes de publicarlos.',
        status: 'Territorio',
        target: 'Mapas',
      },
    ],
    permissions: [
      'Todo lo permitido al Admin Regional',
      'Administrar municipios y establecimientos de Cortés',
      'Gestionar usuarios y permisos dentro de la región',
    ],
    restrictions: [
      'No administra otras regiones',
      'No modifica objetos nacionales ni consulta ITS 1 individual',
    ],
    workflow: [
      'Configurar región',
      'Supervisar municipios',
      'Consolidar Cortés',
      'Enviar a Nivel Central',
    ],
    primaryLabel: 'Administrar región',
    primaryTarget: 'Administración',
  },
  {
    id: 'regional-admin',
    roleName: 'Admin Regional',
    userName: 'Dra. Sonia Aguilar',
    initials: 'SA',
    scopeLabel: 'Región de Cortés',
    scopeDetail: 'Municipios y consolidados de la región',
    privacyLabel: 'Vista regional agregada',
    privacyDetail: 'Sin administración técnica ni ITS 1 individual.',
    dashboardMeta: {
      eyebrow: 'ADMINISTRACIÓN REGIONAL · CORTÉS',
      title: 'Operación regional ITS',
      description: 'Revisión municipal, calidad del dato y consolidación de la Región de Cortés.',
    },
    navItems: [
      'Inicio',
      'Bandeja de revisión',
      'Consolidados',
      'Redes',
      'Mapas',
      'Reportes y exportaciones',
    ],
    metrics: [
      { label: 'Municipios recibidos', value: '1', detail: 'Puerto Cortés', tone: 'green' },
      { label: 'Consolidado regional', value: 'En curso', detail: 'Julio 2026', tone: 'blue' },
      { label: 'Casos reportados', value: '184', detail: 'Información agregada', tone: 'purple' },
      { label: 'Observaciones', value: '3', detail: 'Devueltas al municipio', tone: 'amber' },
    ],
    tasks: [
      {
        title: 'Validar reporte municipal',
        detail: 'Puerto Cortés completó 9 de 12 establecimientos.',
        status: 'Revisión',
        target: 'Bandeja de revisión',
      },
      {
        title: 'Resolver observaciones regionales',
        detail: 'Tres hallazgos de consistencia pendientes.',
        status: 'Calidad',
      },
      {
        title: 'Generar consolidado de Cortés',
        detail: 'Se habilitará después de aprobar Puerto Cortés.',
        status: 'Pendiente',
        target: 'Consolidados',
      },
    ],
    permissions: [
      'Revisar consolidados municipales',
      'Devolver y aprobar reportes agregados',
      'Generar y enviar consolidado regional',
    ],
    restrictions: [
      'No administra usuarios ni estructura territorial',
      'No consulta ITS 1 individual',
    ],
    workflow: [
      'Recibir municipios',
      'Revisar consistencia',
      'Aprobar municipal',
      'Consolidar región',
    ],
    primaryLabel: 'Revisar municipios',
    primaryTarget: 'Bandeja de revisión',
  },
  {
    id: 'municipal-coordinator',
    roleName: 'Coordinadora Municipal',
    userName: 'Dra. Ana Martínez',
    initials: 'AM',
    scopeLabel: 'Puerto Cortés',
    scopeDetail: 'Coordinación municipal · 12 establecimientos',
    privacyLabel: 'Vista consolidada',
    privacyDetail: 'Sin acceso a datos individuales ITS 1.',
    dashboardMeta: {
      eyebrow: 'COORDINACIÓN MUNICIPAL · PUERTO CORTÉS',
      title: 'Resumen epidemiológico',
      description: 'Seguimiento del período, calidad y reportes ITS de los establecimientos.',
    },
    navItems: [
      'Inicio',
      'Bandeja de revisión',
      'Consolidados',
      'Mapas',
      'Redes',
      'Reportes y exportaciones',
    ],
    metrics: [
      { label: 'Casos ITS', value: '184', detail: '+7.6% respecto a junio', tone: 'green' },
      { label: 'Reportes recibidos', value: '9 / 12', detail: '75% de cumplimiento', tone: 'blue' },
      { label: 'En revisión', value: '2', detail: 'ITS 2 de establecimientos', tone: 'purple' },
      { label: 'Pendientes', value: '3', detail: 'Requieren seguimiento', tone: 'amber' },
    ],
    tasks: [
      {
        title: 'Revisar ITS 2 devuelto',
        detail: 'UAPS La Pita tiene tres observaciones.',
        status: 'Devuelto',
        target: 'Bandeja de revisión',
      },
      {
        title: 'Dar seguimiento a reportes faltantes',
        detail: 'Tres establecimientos aún no enviaron.',
        status: 'Pendiente',
      },
      {
        title: 'Preparar consolidado municipal',
        detail: 'Disponible cuando se aprueben los 12 reportes.',
        status: 'Consolidado',
        target: 'Consolidados',
      },
    ],
    permissions: [
      'Revisar y devolver ITS 2',
      'Aprobar reportes de establecimientos',
      'Generar consolidado municipal',
    ],
    restrictions: [
      'No consulta expedientes ni ITS 1 individual',
      'No administra usuarios regionales',
    ],
    workflow: [
      'Recibir ITS 2',
      'Solicitar correcciones',
      'Aprobar establecimientos',
      'Enviar a región',
    ],
    primaryLabel: 'Abrir bandeja',
    primaryTarget: 'Bandeja de revisión',
  },
  {
    id: 'coordination-digitizer',
    roleName: 'Digitadora de Coordinación',
    userName: 'María López',
    initials: 'ML',
    scopeLabel: 'Puerto Cortés',
    scopeDetail: 'Digitación para 12 establecimientos seleccionables',
    privacyLabel: 'Acceso operativo controlado',
    privacyDetail: 'ITS 1 del establecimiento activo y flujo autorizado.',
    dashboardMeta: {
      eyebrow: 'DIGITACIÓN DE COORDINACIÓN · PUERTO CORTÉS',
      title: 'Centro de digitación',
      description:
        'Captura, corrección y preparación de reportes para el establecimiento seleccionado.',
    },
    navItems: ['Inicio', 'Captura ITS 1', 'Reporte ITS 2'],
    metrics: [
      {
        label: 'Establecimiento activo',
        value: '2721',
        detail: 'Policlínico Cornelio Moncada',
        tone: 'green',
      },
      { label: 'Capturas del día', value: '14', detail: 'Dos requieren validación', tone: 'blue' },
      { label: 'ITS 2 preparados', value: '9 / 12', detail: 'Julio 2026', tone: 'purple' },
      { label: 'Correcciones', value: '3', detail: 'Solicitadas por coordinación', tone: 'amber' },
    ],
    tasks: [
      {
        title: 'Corregir registros observados',
        detail: 'UAPS La Pita · tres observaciones de coordinación.',
        status: 'Corrección',
        target: 'Captura ITS 1',
      },
      {
        title: 'Completar ITS 2 de CIS Bajamar',
        detail: 'Faltan validaciones antes del envío.',
        status: 'Borrador',
        target: 'Reporte ITS 2',
      },
      {
        title: 'Registrar atenciones del día',
        detail: 'Policlínico Cornelio Moncada Puerto Cortés.',
        status: 'Captura',
        target: 'Captura ITS 1',
      },
    ],
    permissions: [
      'Seleccionar uno de los 12 establecimientos',
      'Capturar y corregir ITS 1 autorizado',
      'Preparar y enviar ITS 2 a coordinación',
    ],
    restrictions: ['No aprueba reportes', 'No modifica estructura ni usuarios'],
    workflow: [
      'Seleccionar establecimiento',
      'Capturar ITS 1',
      'Preparar ITS 2',
      'Atender correcciones',
    ],
    primaryLabel: 'Capturar ITS 1',
    primaryTarget: 'Captura ITS 1',
  },
  {
    id: 'establishment-manager',
    roleName: 'Responsable de Establecimiento',
    userName: 'Enf. Julia Reyes',
    initials: 'JR',
    scopeLabel: 'CIS Linda Coello',
    scopeDetail: 'Establecimiento 85481 · Puerto Cortés',
    privacyLabel: 'Datos del establecimiento',
    privacyDetail: 'Acceso a ITS 1 e ITS 2 propios.',
    dashboardMeta: {
      eyebrow: 'ESTABLECIMIENTO · CIS LINDA COELLO',
      title: 'Operación del establecimiento',
      description: 'Captura individual, control de calidad y reporte mensual propio.',
    },
    navItems: ['Inicio', 'Captura ITS 1', 'Reporte ITS 2', 'Mapas', 'Reportes y exportaciones'],
    metrics: [
      { label: 'Casos del período', value: '28', detail: '21 nuevos · 7 controles', tone: 'green' },
      {
        label: 'Capturas pendientes',
        value: '2',
        detail: 'Requieren completar procedencia',
        tone: 'blue',
      },
      { label: 'Estado ITS 2', value: 'Borrador', detail: 'Julio 2026', tone: 'purple' },
      { label: 'Observaciones', value: '1', detail: 'Pendiente de corrección', tone: 'amber' },
    ],
    tasks: [
      {
        title: 'Completar dos capturas ITS 1',
        detail: 'Falta procedencia en registros recientes.',
        status: 'Captura',
        target: 'Captura ITS 1',
      },
      {
        title: 'Validar resumen ITS 2',
        detail: 'Confirmar nuevos, controles y total de atenciones.',
        status: 'Borrador',
        target: 'Reporte ITS 2',
      },
      {
        title: 'Responder observación municipal',
        detail: 'Corregir inconsistencia antes del reenvío.',
        status: 'Corrección',
        target: 'Reporte ITS 2',
      },
    ],
    permissions: [
      'Capturar y corregir ITS 1 propio',
      'Generar ITS 2 del establecimiento',
      'Enviar reporte a coordinación municipal',
    ],
    restrictions: ['No cambia de establecimiento', 'No consulta datos de otros establecimientos'],
    workflow: ['Capturar atenciones', 'Validar resumen', 'Enviar ITS 2', 'Responder observaciones'],
    primaryLabel: 'Capturar atención',
    primaryTarget: 'Captura ITS 1',
  },
  {
    id: 'supervisor',
    roleName: 'Supervisor o Consulta',
    userName: 'Dr. Luis Romero',
    initials: 'LR',
    scopeLabel: 'Región de Cortés',
    scopeDetail: 'Consulta agregada según permisos asignados',
    privacyLabel: 'Solo lectura',
    privacyDetail: 'Sin acciones de captura, aprobación o administración.',
    dashboardMeta: {
      eyebrow: 'SUPERVISIÓN Y CONSULTA · CORTÉS',
      title: 'Panel de seguimiento',
      description: 'Indicadores, tendencias e informes dentro del alcance autorizado.',
    },
    navItems: ['Inicio', 'Redes', 'Mapas', 'Reportes y exportaciones'],
    metrics: [
      { label: 'Casos visibles', value: '184', detail: 'Información consolidada', tone: 'green' },
      {
        label: 'Cobertura de reportes',
        value: '75%',
        detail: '9 de 12 establecimientos',
        tone: 'blue',
      },
      { label: 'Tasa ITS / 1,000', value: '4.8', detail: 'Julio 2026', tone: 'purple' },
      { label: 'Alertas visibles', value: '6', detail: 'Solo para seguimiento', tone: 'amber' },
    ],
    tasks: [
      {
        title: 'Consultar tendencia mensual',
        detail: 'Comparar enero a julio de 2026.',
        status: 'Análisis',
      },
      {
        title: 'Explorar mapa regional',
        detail: 'Acercarse a Puerto Cortés y sus establecimientos.',
        status: 'Mapa',
        target: 'Mapas',
      },
      {
        title: 'Generar informe de consulta',
        detail: 'Exportación agregada y auditada.',
        status: 'Reporte',
        target: 'Reportes y exportaciones',
      },
    ],
    permissions: [
      'Consultar indicadores agregados',
      'Explorar mapas dentro del alcance',
      'Generar exportaciones permitidas',
    ],
    restrictions: [
      'No captura ni corrige ITS 1',
      'No aprueba reportes ni administra configuración',
    ],
    workflow: [
      'Seleccionar período',
      'Analizar indicadores',
      'Explorar territorio',
      'Exportar consulta',
    ],
    primaryLabel: 'Explorar mapa',
    primaryTarget: 'Mapas',
  },
];
